# Generated by Django 5.1.3 on 2024-11-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeditem",
            name="og_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="og_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
